from datetime import datetime
from typing import List, Optional

from pydantic import AliasChoices, Field

from constants import MatchEventStatus, MatchEventType
from project_helpers.schemas import BaseSchema


class MatchEventAdd(BaseSchema):
    """One action from the operator console.

    `clientEventId` is generated by the client before the request leaves the
    phone. Replaying it is how a retry after a dropped connection stays safe;
    the server fills one in when a caller omits it.
    """

    type: MatchEventType
    teamId: int
    clientEventId: Optional[str] = Field(None, max_length=64)
    playerId: Optional[int] = None
    assistPlayerId: Optional[int] = None
    minute: Optional[int] = Field(None, ge=0, le=200)
    supersedesEventId: Optional[int] = None


class MatchEventVoid(BaseSchema):
    reason: Optional[str] = Field(None, max_length=200)


class MatchEventItem(BaseSchema):
    id: int
    matchId: int
    clientEventId: Optional[str] = None
    type: MatchEventType
    status: MatchEventStatus
    teamId: int
    playerId: Optional[int] = None
    playerName: Optional[str] = None
    assistPlayerId: Optional[int] = None
    assistName: Optional[str] = None
    minute: Optional[int] = None
    createdAt: datetime
    createdById: Optional[int] = None
    createdByName: Optional[str] = None
    voidedAt: Optional[datetime] = None
    voidedByName: Optional[str] = None
    voidReason: Optional[str] = None
    supersedesEventId: Optional[int] = None


class MatchEventListParams(BaseSchema):
    includeVoided: bool = Field(
        False, validation_alias=AliasChoices("includeVoided", "include_voided")
    )


class MatchEventListResponse(BaseSchema):
    data: List[MatchEventItem] = []


class MatchClockAction(BaseSchema):
    """Optional explicit minute when correcting the clock by hand."""

    minute: Optional[int] = Field(None, ge=0, le=200)


class MatchReopen(BaseSchema):
    reason: str = Field(..., min_length=3, max_length=200)


class MatchEventWriteResponse(BaseSchema):
    """What the operator console needs back after one action.

    Carries the recalculated score and clock alongside the event, so the phone
    does not need a second request to refresh the header, and `created` tells a
    retry apart from a first submission.
    """

    event: MatchEventItem
    created: bool = True
    scoreHome: Optional[int] = None
    scoreAway: Optional[int] = None
    currentMinute: Optional[int] = None
